.TH "todo" 3 "Sat Feb 10 2018" "Version 1.1" "log4cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBlog4cpp::PropertyConfiguratorImpl::configureCategory\fP (const std::string &categoryname)\fP" 1c
setting other properties like 'additivity'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcategoryname\fP Name of the category to configure\&. The name 'rootCategory' refers to the root Category\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIConfigureFailure\fP if the method encountered a read or syntax error\&. 
.RE
.PP
.PP

